#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    := DALComm
CONFIG    := 
STRIP_FLAG:= N
INCLUDE   :=
LIB       :=
LOCAL_SRC :=

#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
