#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    := DALComm
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   :=

LIB       :=

LOCAL_SRC :=

RELEASE_JCE += DbPool.h MultiDbPool.h DalDbInterface.h

#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
