APP       := ServerEngine
TARGET    := LoginServer
#CFLAGS := -fPIC
MFLAGS    := 64
CONFIG    := 
STRIP_FLAG:= N


LOCAL_SRC	+= $(wildcard *.cpp)

include /home/tarsproto/ServerEngine/CommInclude.mk
include /home/tarsproto/ServerEngine/CommLib.mk
include /usr/local/tars/cpp/makefile/makefile.tars

